<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/jetelain/weatherstats</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Description>Library for reading ERA5 average weather statistics.</Description>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Authors>Julien Etelain</Authors>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>
	<PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>
	
	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
